Repository 2024-2-SOLUX-in-space/inspace-backend, pull requests merged in 2025-01, with the labels that each got.

#8 FEAT: 로그아웃 구현
  .idea/misc.xml
  inspace-be/.gradle/8.11.1/checksums/checksums.lock
  inspace-be/.gradle/8.11.1/checksums/md5-checksums.bin
  inspace-be/.gradle/8.11.1/checksums/sha1-checksums.bin
  inspace-be/.gradle/8.11.1/executionHistory/executionHistory.bin
  inspace-be/.gradle/8.11.1/executionHistory/executionHistory.lock
  inspace-be/.gradle/8.11.1/fileHashes/fileHashes.bin
  inspace-be/.gradle/8.11.1/fileHashes/fileHashes.lock
  inspace-be/.gradle/8.11.1/fileHashes/resourceHashesCache.bin
  inspace-be/.gradle/buildOutputCleanup/buildOutputCleanup.lock
  inspace-be/.gradle/buildOutputCleanup/outputFiles.bin
  inspace-be/build.gradle
  inspace-be/build/classes/java/main/jpabasic/inspacebe/config/SwaggerConfig.class
  inspace-be/build/tmp/compileJava/previous-compilation-data.bin
  inspace-be/gradlew
  inspace-be/src/main/java/jpabasic/inspacebe/config/JwtAuthenticationFilter.java
  inspace-be/src/main/java/jpabasic/inspacebe/config/JwtProvider.java
  inspace-be/src/main/java/jpabasic/inspacebe/config/SecurityConfig.java
  inspace-be/src/main/java/jpabasic/inspacebe/config/SwaggerConfig.java
  inspace-be/src/main/java/jpabasic/inspacebe/controller/AuthController.java
  inspace-be/src/main/java/jpabasic/inspacebe/controller/UserController.java
  inspace-be/src/main/java/jpabasic/inspacebe/dto/LoginRequest.java
  inspace-be/src/main/java/jpabasic/inspacebe/dto/PasswordResetRequest.java
  inspace-be/src/main/java/jpabasic/inspacebe/dto/RegisterRequest.java
  inspace-be/src/main/java/jpabasic/inspacebe/dto/UpdateUserRequest.java
  inspace-be/src/main/java/jpabasic/inspacebe/entity/User.java
  inspace-be/src/main/java/jpabasic/inspacebe/repository/UserRepository.java
  inspace-be/src/main/java/jpabasic/inspacebe/service/EmailService.java
Labels: 🤍영서🤍

#13 Feature/home apis
  inspace-be/.gitignore
  inspace-be/build.gradle
  inspace-be/src/main/java/jpabasic/inspacebe/controller/ItemController.java
  inspace-be/src/main/java/jpabasic/inspacebe/controller/SpaceController.java
  inspace-be/src/main/java/jpabasic/inspacebe/converter/CtypeAttributeConverter.java
  inspace-be/src/main/java/jpabasic/inspacebe/dto/SpaceDto.java
  inspace-be/src/main/java/jpabasic/inspacebe/entity/Item.java
  inspace-be/src/main/java/jpabasic/inspacebe/entity/Space.java
  inspace-be/src/main/java/jpabasic/inspacebe/repository/ItemRepository.java
  inspace-be/src/main/java/jpabasic/inspacebe/repository/SpaceRepository.java
  inspace-be/src/main/java/jpabasic/inspacebe/service/ItemService.java
  inspace-be/src/main/java/jpabasic/inspacebe/service/SpaceService.java
Labels: 🍒민서🍒, FEAT

#17 [FIX] 변수명 수정
  inspace-be/.gradle/8.11.1/checksums/checksums.lock
  inspace-be/.gradle/8.11.1/checksums/md5-checksums.bin
  inspace-be/.gradle/8.11.1/checksums/sha1-checksums.bin
  inspace-be/.gradle/8.11.1/executionHistory/executionHistory.lock
  inspace-be/.gradle/8.11.1/fileHashes/fileHashes.lock
  inspace-be/.gradle/buildOutputCleanup/buildOutputCleanup.lock
  inspace-be/build.gradle
  inspace-be/settings.gradle
  inspace-be/src/main/java/jpabasic/inspacebe/service/SpaceService.java
Labels: 🍒민서🍒, FIX

#18 [FEAT] Follow 모델 추가
  inspace-be/src/main/java/jpabasic/inspacebe/entity/Follow.java
  inspace-be/src/main/java/jpabasic/inspacebe/entity/User.java
  inspace-be/src/main/java/jpabasic/inspacebe/repository/FollowRepository.java
Labels: FEAT

#20 [FEAT] 공간 수정/조회/삭제/생성 기능 완료
  inspace-be/src/main/java/jpabasic/inspacebe/controller/SpaceController.java
  inspace-be/src/main/java/jpabasic/inspacebe/converter/ResponseMessage.java
  inspace-be/src/main/java/jpabasic/inspacebe/dto/SpaceDto.java
  inspace-be/src/main/java/jpabasic/inspacebe/entity/Page.java
  inspace-be/src/main/java/jpabasic/inspacebe/entity/Space.java
  inspace-be/src/main/java/jpabasic/inspacebe/entity/User.java
  inspace-be/src/main/java/jpabasic/inspacebe/repository/SpaceRepository.java
  inspace-be/src/main/java/jpabasic/inspacebe/repository/UserRepository.java
  inspace-be/src/main/java/jpabasic/inspacebe/service/SpaceService.java
Labels: 🍒민서🍒, FEAT
